// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwaEnerjiSistemleri.Models;

#nullable disable

namespace SwaEnerjiSistemleri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Dagiticilar", b =>
                {
                    b.Property<int>("DagiticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DagiticiId"), 1L, 1);

                    b.Property<string>("DagiticiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DagiticiSehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MevcutTrafoSayisi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamTuketilenElektrik")
                        .HasColumnType("int");

                    b.Property<int>("ToplamUretilenElektrik")
                        .HasColumnType("int");

                    b.HasKey("DagiticiId");

                    b.ToTable("Dagiticilars");
                });

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Firmalar", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"), 1L, 1);

                    b.Property<int>("DagiticiId")
                        .HasColumnType("int");

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmaId");

                    b.HasIndex("DagiticiId");

                    b.ToTable("Firmalars");
                });

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Sehirler", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SehirId"), 1L, 1);

                    b.Property<string>("SehirAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SehirMerkezi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirlers");
                });

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Tuketiciler", b =>
                {
                    b.Property<int>("TuketiciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TuketiciId"), 1L, 1);

                    b.Property<DateTime>("AbonelikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FaturaKesimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FaturaTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<int>("SayacNo")
                        .HasColumnType("int");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("TuketiciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuketiciSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TuketiciId");

                    b.HasIndex("FirmaId");

                    b.HasIndex("SehirId");

                    b.ToTable("Tuketicilers");
                });

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Firmalar", b =>
                {
                    b.HasOne("SwaEnerjiSistemleri.Models.Dagiticilar", "Dagiticilar")
                        .WithMany()
                        .HasForeignKey("DagiticiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dagiticilar");
                });

            modelBuilder.Entity("SwaEnerjiSistemleri.Models.Tuketiciler", b =>
                {
                    b.HasOne("SwaEnerjiSistemleri.Models.Firmalar", "Firmalar")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwaEnerjiSistemleri.Models.Sehirler", "Sehirler")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmalar");

                    b.Navigation("Sehirler");
                });
#pragma warning restore 612, 618
        }
    }
}
